### ISSUE TITLE
/dwv/viewers/mobile HTTP 404

### ISSUE THREAD

**Issue by GitenAR** [ivmartel/dwv-dcm4chee-web#3]
Dear ivmartel, I followed the install steps as described in https://github.com/ivmartel/dwv-dcm4chee-web.

I'm have DC4CHE 2.18.1 and running into the following problem web navigating the mobile page:

![2017-02-04_12-51-26](https://cloud.githubusercontent.com/assets/11651487/22619694/204816ac-ead9-11e6-8b05-1f9d16a095aa.png)

Thank you in advance!

**Comment by ivmartel** [comment]
Hi, not sure what is happening. Are your sure  you have the `dwv.war` in the `server\default\deploy` folder?
I have not tried the plugin with this version of dcm4che, I will and come back to you.

**Comment by ivmartel** [comment]
Ok, I tested dcm4chee 2.18.1 and it works. The only difference I can see now would be the IP, I mainly test using localhost.

**Comment by ivmartel** [comment]
Closing for now. I hope you found a solution to your problem. If so can you share? If not feel free to comment.
