### ISSUE TITLE
open dcm direct url

### ISSUE THREAD

**Issue by amendoinn** [ivmartel/dwv-dcm4chee-web#4]
Hello guys

I'm trying to open a dcm file in dwv directly from a url, but I get the attached error message, however I can access the file directly, have some idea of what password, I tried both with the normal url both encode

![erro](https://cloud.githubusercontent.com/assets/26126495/23487517/62d03d38-fec5-11e6-8898-813dfce2188d.PNG)
![url](https://cloud.githubusercontent.com/assets/26126495/23487524/6d47725e-fec5-11e6-96be-3a8fed315898.PNG)

**Comment by ivmartel** [comment]
Without a server (such as your PACS), you cannot access local files using the url input. This is not possible in Javascript and gives 'Cross origin requests' errors (check out the console window of your browser). What you can do is load them via the open file.
For more details. check out this wiki page of dwv: [requesterror](https://github.com/ivmartel/dwv/wiki/Error-Messages#requesterror).

**Comment by ivmartel** [comment]
I hope I answered the question, feel free to comment if not. Closing for now.
